apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-oidc-delegator
spec:
  template:
    spec:
      containers:
      - name: kubernetes-oidc-delegator
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi