apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-oidc-delegator-config
  labels:
    app: kubernetes-oidc-delegator
data:
  server-host: "https://your-server-host.example.com"
  issuer: "https://kubernetes.default.svc.cluster.local"