version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kubernetes-oidc-delegator
    binary: kubernetes-oidc-delegator
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers:
  - id: kubernetes-oidc-delegator
    goos: linux
    goarch: amd64
    ids:
      - kubernetes-oidc-delegator
    image_templates:
      - "ghcr.io/bear-san/kubernetes-oidc-delegator:{{ .Tag }}"
      - "ghcr.io/bear-san/kubernetes-oidc-delegator:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

archives:
  - id: kubernetes-oidc-delegator
    builds:
      - kubernetes-oidc-delegator
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'