apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubernetes-oidc-delegator-development

resources:
- ../../base

namespace: development

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

commonLabels:
  environment: development

images:
- name: ghcr.io/bear-san/kubernetes-oidc-delegator
  newTag: dev